### GET All items 
GET http://127.0.0.1:5000/items HTTP/1.1


### GET Single items 
GET http://127.0.0.1:5000/items/1d125599-9cc1-447d-8885-459f9258f194 HTTP/1.1


### ADD Single items 
POST http://127.0.0.1:5000/items  HTTP/1.1
Content-Type: application/json

{
    "name": "just a name",
    "tier": "no tier"
}

### Delete Single item with id
DELETE http://127.0.0.1:5000/items/c89608cf-39a7-4589-9eea-173ae87192da HTTP/1.1


### Update a single item
PUT http://127.0.0.1:5000/items/1d125599-9cc1-447d-8885-459f9258f194 HTTP/1.1
Content-Type: application/json

{
    "name": "Dahir",
    "tier": "Dahir"
}
