### GET All items 
GET http://127.0.0.1:5000/items HTTP/1.1


### GET Single items 
GET http://127.0.0.1:5000/items/0953753c-3268-48e3-ad12-62734c24dd59 HTTP/1.1


### ADD Single items 
POST http://127.0.0.1:5000/items  HTTP/1.1
Content-Type: application/json

{
    "name": 10
    
}

### Delete Single item with id
DELETE http://127.0.0.1:5000/items/a409733d-d576-4e76-92c9-209b5178878e HTTP/1.1


### Update a single item
PUT http://127.0.0.1:5000/items/e925babb-99ab-4992-a752-a991befe251f HTTP/1.1
Content-Type: application/json

{
    "name": "s1",
    "email": "s2@capitalone.com",
    "phone_number": "1111111111",
    "hire_date": "1000-01-01",
    "job_id": "100",
    "salary": 150000,
    "commission_pct": 100,
    "manager_id": "20"
}
